# Generated by Django 3.0.4 on 2020-03-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(default=233, max_length=12),
        ),
    ]
